<?php

namespace Database\Seeders;

use App\Enums\AuthorType;
use App\Enums\Visibility;
use App\Models\Category;
use App\Models\Story;
use App\Models\Tag;
use App\Models\User;
use Illuminate\Database\Seeder;

class StorySeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();

        if (! $user) {
            $this->command->error('No user found. Please run DatabaseSeeder first.');
            return;
        }

        $categories = Category::all()->keyBy('slug');

        if ($categories->isEmpty()) {
            $this->command->error('No categories found. Please run CategorySeeder first.');
            return;
        }

        $stories = $this->getStories();

        foreach ($stories as $storyData) {
            $category = $categories->get($storyData['category']);

            if (! $category) {
                continue;
            }

            $story = Story::create([
                'title' => $storyData['title'],
                'content' => '<p>' . implode('</p><p>', explode("\n\n", $storyData['content'])) . '</p>',
                'excerpt' => $storyData['excerpt'],
                'user_id' => $user->id,
                'author_type' => $storyData['author_type'],
                'author_text' => $storyData['author_text'] ?? null,
                'category_id' => $category->id,
                'visibility' => Visibility::Public,
                'hide_creator' => false,
                'hide_author' => false,
                'anonymize_names' => false,
                'published_at' => now()->subDays(rand(1, 365)),
            ]);

            if (! empty($storyData['tags'])) {
                $story->syncTags($storyData['tags']);
            }
        }

        $this->command->info('Created ' . count($stories) . ' stories.');
    }

    private function getStories(): array
    {
        return [
            // INSPIRATION (13 stories)
            [
                'title' => 'The Marathon at 65',
                'content' => "My neighbor Martha told me she'd never run more than a mile in her life. Then she turned 65 and decided to train for a marathon.\n\nEvery morning at 5 AM, I'd see her shuffling past my window in the dark. Rain, shine, or snow—she was out there. Some days she could barely make it around the block. But she kept going.\n\nEighteen months later, I watched her cross the finish line of the Chicago Marathon. Her time didn't matter. What mattered was the look on her face—pure, unfiltered joy.\n\n\"It's never too late,\" she told me afterward, still catching her breath. \"It's only too late if you never start.\"",
                'excerpt' => 'A 65-year-old woman proves it\'s never too late to start something new.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['running', 'age', 'determination', 'goals'],
            ],
            [
                'title' => 'The Teacher Who Changed Everything',
                'content' => "I was failing seventh grade. Not because I couldn't do the work, but because I'd convinced myself I was stupid. Every test came back red, and I'd stopped trying.\n\nMr. Patterson noticed. Instead of giving up on me like everyone else, he asked me to stay after class one day.\n\n\"I see you,\" he said. \"I see how smart you are when you think no one's watching. What would happen if you let yourself try?\"\n\nNo one had ever said that to me before. That afternoon, I did my homework for the first time in months. Then I did it the next day too.\n\nTwenty years later, I'm a teacher myself. And every year, I look for the kid who's given up—and I tell them exactly what Mr. Patterson told me.",
                'excerpt' => 'One teacher\'s belief changed the trajectory of a struggling student\'s life.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['education', 'belief', 'mentorship', 'potential'],
            ],
            [
                'title' => 'Rebuilding After the Fire',
                'content' => "We lost everything in the fire. Thirty years of memories, photographs, my grandmother's recipes, the kids' baby books—all gone in three hours.\n\nFor weeks, I couldn't get out of bed. The grief was suffocating. How do you rebuild a life from ashes?\n\nThen my daughter drew me a picture. It was our house, surrounded by flowers. \"This is our new house,\" she said. \"It's going to be even better because we'll fill it with new happy things.\"\n\nShe was right. We couldn't replace what we lost, but we could create something new. Three years later, our walls are covered with new memories—and somehow, they feel just as precious.",
                'excerpt' => 'A family discovers that new beginnings can emerge from devastating loss.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['resilience', 'family', 'loss', 'new-beginnings'],
            ],
            [
                'title' => 'The Rejection That Led to Success',
                'content' => "My manuscript was rejected 47 times. Forty-seven agents told me my story wasn't good enough, that no one would want to read it.\n\nAfter rejection number 30, I almost quit. I'd spent three years writing that book, and it seemed like the universe was telling me to give up.\n\nBut something in me refused. I revised the manuscript one more time, made it tighter, stronger. I sent it out again.\n\nAgent number 48 said yes. A year later, my book hit the bestseller list. Those 47 rejections weren't failures—they were practice. They made me better.\n\nNow I keep those rejection letters in a frame on my office wall. They remind me that \"no\" is often just the beginning.",
                'excerpt' => '47 rejections became the foundation for bestselling success.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['writing', 'rejection', 'persistence', 'success'],
            ],
            [
                'title' => 'Finding My Voice at 40',
                'content' => "For forty years, I let other people speak for me. I was the quiet one, the listener, the person who nodded along in meetings while my ideas stayed trapped inside my head.\n\nThen I joined a Toastmasters group on a dare from my sister. My first speech was a disaster—my hands shook so badly I could barely hold my notes. But I went back the next week, and the week after that.\n\nSomething strange happened. The more I practiced using my voice, the more I realized I had something worth saying. Now I speak at conferences. I lead meetings. I mentor young women who remind me of my younger self.\n\nYour voice matters. It took me forty years to learn that, but it's never too late to be heard.",
                'excerpt' => 'A lifetime of silence ended when she finally found her voice.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['public-speaking', 'confidence', 'growth', 'women'],
            ],
            [
                'title' => 'The Immigrant\'s Dream',
                'content' => "My father arrived in this country with eight dollars in his pocket and a dictionary he'd memorized on the boat ride over.\n\nHe worked three jobs while learning English from TV sitcoms. He saved every penny, lived on rice and beans, and sent money home to his mother.\n\nTwenty years later, he owned his own restaurant. The day he paid off the mortgage, he sat in the empty dining room and cried. Not from sadness, but from the overwhelming realization that his impossible dream had become real.\n\n\"In my village,\" he told me, \"people said I was crazy to leave. But I knew there was more for me somewhere. I just had to be brave enough to find it.\"",
                'excerpt' => 'From eight dollars to business owner—one immigrant\'s journey to the American dream.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['immigration', 'hard-work', 'dreams', 'family'],
            ],
            [
                'title' => 'The Power of \"What If\"',
                'content' => "I spent most of my life saying \"I can't.\" I can't change careers. I can't learn to paint. I can't travel alone. The list was endless.\n\nThen my therapist challenged me to replace \"I can't\" with \"What if I could?\" It seemed too simple to work.\n\nBut something shifted. What if I could change careers? Well, I'd need to go back to school. What if I could do that? I'd need to save money and adjust my schedule.\n\nSuddenly, impossible things had steps. Within two years, I'd switched careers, started painting on weekends, and booked my first solo trip abroad.\n\nThe only thing standing between me and my dreams was the story I was telling myself.",
                'excerpt' => 'Changing one word changed everything.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['mindset', 'self-improvement', 'therapy', 'possibility'],
            ],
            [
                'title' => 'Standing Up Again',
                'content' => "The accident left me paralyzed from the waist down. Doctors said I'd never walk again. For months, I believed them.\n\nThen I met David in physical therapy. He'd been in a similar accident ten years earlier. The doctors had told him the same thing. That day, he walked into the room on his own two feet.\n\n\"They told me what was impossible,\" he said. \"But they didn't know my spirit.\"\n\nI started my real recovery that day. It took four years, countless setbacks, and more pain than I knew existed. But last month, I walked my daughter down the aisle.\n\nImpossible is just an opinion.",
                'excerpt' => 'Defying medical expectations through sheer determination.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['disability', 'recovery', 'determination', 'medical'],
            ],
            [
                'title' => 'The Business Born in a Kitchen',
                'content' => "I started making soap in my kitchen as a way to cope with anxiety. There was something meditative about measuring ingredients, stirring slowly, watching chemistry happen in real time.\n\nI gave bars to friends, who gave them to their friends. Someone suggested I sell them at a farmer's market. I laughed—who would pay for homemade soap?\n\nTurns out, a lot of people. That first Saturday, I sold out in two hours. Now my \"anxiety hobby\" employs twelve people and ships to all fifty states.\n\nSometimes your coping mechanism is actually your calling. You just have to give it room to grow.",
                'excerpt' => 'An anxiety coping mechanism became a thriving business.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['entrepreneurship', 'anxiety', 'creativity', 'small-business'],
            ],
            [
                'title' => 'Never Too Old to Learn',
                'content' => "My grandmother got her GED at 78. She'd dropped out of school in the eighth grade to help on the family farm and always regretted it.\n\n\"I'm going to die educated,\" she announced one Thanksgiving. We thought she was joking.\n\nShe wasn't. She enrolled in classes, stayed up late studying, and asked her great-grandchildren to help her with math. The day she passed her exam, she cried harder than at any funeral she'd ever attended.\n\n\"I proved something to myself,\" she said. \"It doesn't matter how many years you waste. What matters is what you do with the years you have left.\"",
                'excerpt' => 'At 78, she finally got the education she\'d always wanted.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['education', 'age', 'determination', 'grandparents'],
            ],
            [
                'title' => 'From Homeless to Harvard',
                'content' => "At sixteen, I was living in my car. My mother's addiction had spiraled, and I had nowhere else to go. I showered at the YMCA and did homework under streetlights.\n\nMy English teacher noticed I was wearing the same clothes every day. Instead of calling CPS, she called me into her office and asked how she could help.\n\nThat conversation changed my life. She connected me with resources, helped me apply for scholarships, and wrote college recommendations that made me cry.\n\nFive years later, I walked through Harvard's gates as a freshman. I called her from my dorm room that night.\n\n\"You saw me,\" I told her. \"When no one else did, you saw me.\"",
                'excerpt' => 'One teacher\'s compassion helped a homeless teen reach the Ivy League.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['education', 'homelessness', 'mentorship', 'overcoming'],
            ],
            [
                'title' => 'The Comeback Kid',
                'content' => "At 35, I was bankrupt, divorced, and living in my parents' basement. Everything I'd built had crumbled. Friends stopped calling. I stopped believing in myself.\n\nMy father, a man of few words, sat with me one night. \"You're not done,\" he said. \"You're just getting started again.\"\n\nI didn't believe him. But I started anyway. I took a minimum wage job. I paid off one debt at a time. I rebuilt my credit, my confidence, my life—one tiny step after another.\n\nTen years later, I'm running a successful consulting firm. My father's words hang framed in my office: \"You're not done. You're just getting started again.\"",
                'excerpt' => 'From bankruptcy and divorce to business success—one step at a time.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['comeback', 'failure', 'family', 'business'],
            ],
            [
                'title' => 'Painting in the Dark',
                'content' => "When I lost my sight at 52, I thought my life as an artist was over. How could I paint what I couldn't see?\n\nBut art wouldn't let me go. I started experimenting with texture, with raised canvases I could feel. I mixed colors from memory, trusting my hands to know what my eyes no longer could.\n\nMy first \"blind\" painting sold at a gallery showing. The buyer said it was the most emotionally powerful piece she'd ever seen.\n\n\"You painted with your soul,\" she told me. \"I can feel everything you couldn't see.\"\n\nLosing my sight didn't end my art. It transformed it into something deeper.",
                'excerpt' => 'Blindness couldn\'t stop an artist\'s creative spirit.',
                'category' => 'inspiration',
                'author_type' => AuthorType::Self,
                'tags' => ['art', 'blindness', 'creativity', 'adaptation'],
            ],

            // GRATITUDE (12 stories)
            [
                'title' => 'The Gift of Ordinary Days',
                'content' => "After my cancer diagnosis, everything changed. Not just the obvious things—the treatments, the fear, the uncertainty. What changed most was how I saw my regular Tuesday mornings.\n\nBefore cancer, I'd rush through breakfast, annoyed at traffic, stressed about deadlines. Now I linger over my coffee. I notice how the light comes through the kitchen window. I call my mother just to hear her voice.\n\nI'm in remission now, but I never want to forget what cancer taught me: there is no such thing as an ordinary day. Every boring, routine, unremarkable moment is a gift we're not guaranteed.",
                'excerpt' => 'Cancer taught her to treasure the ordinary moments.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['cancer', 'perspective', 'health', 'mindfulness'],
            ],
            [
                'title' => 'Thank You, Stranger',
                'content' => "I never got your name. You were the woman on the subway who noticed I was crying and silently handed me a packet of tissues. You didn't ask what was wrong. You didn't try to fix it. You just acknowledged that I was hurting and offered what you had.\n\nThat small gesture—from a complete stranger—broke through my numbness in a way nothing else could. I'd been told I was being dramatic, that I should be over it by now. But you, a stranger, showed me simple compassion without judgment.\n\nWherever you are, thank you. Your kindness mattered more than you'll ever know.",
                'excerpt' => 'A stranger\'s simple gesture broke through the pain.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['strangers', 'kindness', 'compassion', 'healing'],
            ],
            [
                'title' => 'Grateful for the Struggle',
                'content' => "I used to resent my difficult childhood. The poverty, the instability, the things other kids had that I didn't. It took me years of therapy to see it differently.\n\nThose hard years taught me resilience. They showed me what truly matters. They gave me empathy for others who struggle. Every obstacle I overcame added to my strength.\n\nI'm not grateful that bad things happened. I'm grateful for who I became because of them. There's a difference—and finding it changed my entire relationship with my past.",
                'excerpt' => 'Finding gratitude not for hardship, but for growth through hardship.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['childhood', 'resilience', 'therapy', 'perspective'],
            ],
            [
                'title' => 'My Mother\'s Hands',
                'content' => "I was helping my mother in the kitchen when I really noticed her hands for the first time. Wrinkled now, spotted with age, but still so capable.\n\nThose hands changed my diapers and packed my school lunches. They applauded at my recitals and wiped my tears. They held mine through every hard moment and every joyful one.\n\nI reached over and took her hand in mine. \"Thank you,\" I said. She looked confused. \"For what?\"\n\n\"For everything your hands have done for me.\"\n\nShe squeezed my hand back, and we stood there in the kitchen, connected by something deeper than words.",
                'excerpt' => 'A moment of gratitude for a mother\'s lifelong care.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['mother', 'family', 'aging', 'love'],
            ],
            [
                'title' => 'The Gift of Failure',
                'content' => "I'm grateful I didn't get my dream job. At the time, the rejection devastated me. I'd prepared for months, and they chose someone else.\n\nBut that closed door pushed me in a different direction. I started my own business. I met my future spouse at a networking event I only attended because I was job hunting. I discovered strengths I never knew I had.\n\nLooking back, getting that job would have been a detour from my true path. Thank you, universe, for knowing what I needed better than I did.",
                'excerpt' => 'A job rejection led to an unexpected and better life.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['career', 'rejection', 'destiny', 'opportunity'],
            ],
            [
                'title' => 'Running Water',
                'content' => "I spent three months volunteering in a village without running water. Every day, women and children walked miles to fill jugs from a river. Every drop was precious.\n\nWhen I came home, I stood in my shower and cried. Clean water, falling endlessly, at the perfect temperature. I'd never thought about it before—it was just always there.\n\nNow I never take a shower without thinking of those women. I never waste water without remembering what it costs. Gratitude lives in the details we usually ignore.",
                'excerpt' => 'Volunteering abroad transformed her relationship with water.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['volunteering', 'perspective', 'water', 'privilege'],
            ],
            [
                'title' => 'The Teacher I Finally Thanked',
                'content' => "For twenty years, I'd been meaning to write to Mrs. Chen, my high school art teacher. She saw potential in me when I saw none. She let me stay late in the art room when home wasn't safe. She wrote the recommendation that got me into college.\n\nI kept putting off that letter. Then I saw her obituary.\n\nThe grief was crushing—not just for her death, but for my years of silence. I'd meant to thank her eventually. Eventually never came.\n\nNow I write thank you letters immediately. I call people to tell them they matter. I refuse to let gratitude wait for \"someday\" again.",
                'excerpt' => 'A lesson in not waiting to express thanks.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['teacher', 'regret', 'appreciation', 'mentorship'],
            ],
            [
                'title' => 'Grateful for My Body',
                'content' => "I spent decades at war with my body. Too fat, too slow, too imperfect. I criticized every curve, every flaw, every limitation.\n\nThen my body carried me through cancer treatment. It fought when I couldn't. It healed when I had no hope left. It kept showing up for me even when I'd spent years being cruel to it.\n\nNow I look in the mirror differently. Thank you, body, for being strong when I was weak. Thank you for healing. Thank you for being mine.\n\nI'm done fighting you. From now on, we're on the same team.",
                'excerpt' => 'Illness transformed her relationship with her body.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['body-image', 'cancer', 'healing', 'self-love'],
            ],
            [
                'title' => 'The Neighbor Who Noticed',
                'content' => "When my husband died, I disappeared. I stopped leaving the house, stopped answering the phone, stopped eating regular meals.\n\nMy neighbor Margaret noticed. She didn't push or pry. She just started leaving dinner on my porch every evening. A pot of soup. A casserole. A plate of cookies.\n\nThose meals saved me. Not just nutritionally—emotionally. Knowing someone saw me, cared about me, thought of me every single day. It was a lifeline I didn't know I needed.\n\nThank you, Margaret. Your consistency kept me alive long enough to want to live again.",
                'excerpt' => 'A neighbor\'s daily kindness became a lifeline through grief.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['grief', 'neighbors', 'kindness', 'widow'],
            ],
            [
                'title' => 'Finding Gratitude in Pain',
                'content' => "My chronic pain taught me something unexpected: how to appreciate the moments between.\n\nWhen the pain is bad, everything shrinks to survival. But when it eases, even slightly, I feel genuine joy. A moment without pain becomes precious. A day of mild discomfort feels like victory.\n\nI've learned to celebrate what I used to ignore. A morning where I can make breakfast. An afternoon where I can take a short walk. An evening without tears.\n\nPain taught me that gratitude isn't about having everything. It's about noticing what you do have—especially on the hard days.",
                'excerpt' => 'Chronic pain revealed a deeper kind of gratitude.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['chronic-illness', 'pain', 'perspective', 'mindfulness'],
            ],
            [
                'title' => 'Letter to My Younger Self',
                'content' => "Dear Twenty-Year-Old Me,\n\nI know you're scared. I know you feel lost and alone and sure you're doing everything wrong. I'm writing from your future to tell you something important: you're going to be okay.\n\nNot perfect—okay. And okay is more than enough.\n\nThank you for not giving up. Thank you for making choices that felt impossible at the time. Thank you for surviving the nights that seemed endless.\n\nBecause of you, I have a life I love. Because you kept going, I got to meet my children, find my partner, discover my purpose.\n\nI'm so grateful you held on.\n\nWith love,\nForty-Year-Old You",
                'excerpt' => 'A letter of gratitude to herself, across two decades.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['self-reflection', 'survival', 'perspective', 'mental-health'],
            ],
            [
                'title' => 'The Privilege of Boredom',
                'content' => "My grandmother survived a war. She fled her country with nothing, lost half her family, spent years not knowing if she'd live another day.\n\nWhen I complained about being bored one afternoon, she smiled. \"Boredom,\" she said, \"means you are safe. It means no one is chasing you, no bombs are falling, no one you love is dying.\"\n\nI never saw boredom the same way again. Now, when nothing exciting is happening, I pause. This ordinary, uneventful moment? My grandmother would have given anything for it.\n\nBoredom is a privilege. And I'm finally grateful for it.",
                'excerpt' => 'A grandmother\'s wisdom reframed the meaning of boredom.',
                'category' => 'gratitude',
                'author_type' => AuthorType::Self,
                'tags' => ['war', 'grandparents', 'perspective', 'safety'],
            ],

            // KINDNESS (13 stories)
            [
                'title' => 'The Coffee Shop Angel',
                'content' => "The woman in front of me at the coffee shop paid for my order. \"Pass it on,\" she said with a wink before leaving.\n\nIt was just a five-dollar coffee. But that morning, I was struggling. My bank account was nearly empty, I'd just lost my job, and I'd treated myself to coffee as a small comfort.\n\nHer kindness made me cry in the parking lot. Not because of the money, but because someone saw a stranger and chose to be generous anyway.\n\nI pass it on every chance I get now. You never know what someone is carrying or how much a small gesture might mean.",
                'excerpt' => 'A stranger\'s five-dollar kindness arrived at the perfect moment.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['strangers', 'generosity', 'coffee', 'pay-it-forward'],
            ],
            [
                'title' => 'The Boy Who Sat Alone',
                'content' => "My son noticed a boy sitting alone at lunch every day. No one talked to him. No one sat with him. He just ate in silence and left.\n\nWithout any prompting from us, my son started sitting with him. At first, the boy didn't talk. But my son kept showing up, day after day, just being present.\n\nWeeks later, the boy started talking. Months later, they were best friends. The boy's mother called me crying, thanking us. Her son had been contemplating suicide. My son's simple kindness—just sitting with him—had given him a reason to stay.\n\nNever underestimate the power of showing up.",
                'excerpt' => 'A child\'s simple act of sitting with someone saved a life.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['children', 'friendship', 'loneliness', 'suicide-prevention'],
            ],
            [
                'title' => 'The Mechanic\'s Gift',
                'content' => "My car broke down three states from home. I pulled into the nearest mechanic, terrified of what it would cost—money I didn't have.\n\nThe mechanic, an older man named Earl, looked at my car and then at me. \"It's a simple fix,\" he said. \"Won't take long.\"\n\nAn hour later, he handed me my keys. \"No charge.\" I protested. He shook his head. \"Someone helped me once when I was stranded. This is how I pay it back.\"\n\nI send Earl a Christmas card every year. And I've stopped to help three stranded motorists since then. His kindness keeps multiplying.",
                'excerpt' => 'A mechanic\'s generosity set off a chain of kindness.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['strangers', 'generosity', 'cars', 'pay-it-forward'],
            ],
            [
                'title' => 'Flowers for No Reason',
                'content' => "Every Friday, my grandfather bought my grandmother flowers. Not for birthdays, not for anniversaries—just because it was Friday.\n\n\"She doesn't need a reason to feel loved,\" he'd say. \"She should feel it all the time.\"\n\nThey were married for fifty-three years. When he passed, we found a drawer full of the cards he'd written her—one for every bouquet, decades of tiny love notes.\n\nNow I buy my spouse flowers every Friday. It's a small thing, but small things add up. And love expressed is always better than love assumed.",
                'excerpt' => 'A grandfather\'s Friday tradition taught lasting lessons about love.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['marriage', 'grandparents', 'love', 'traditions'],
            ],
            [
                'title' => 'The Anonymous Scholarship',
                'content' => "I almost didn't go to college. My family had no money, and loans felt impossible. Then I received a letter: I'd been awarded a full scholarship from an anonymous donor.\n\nI never learned who paid for my education. I wrote thank you letters to the scholarship office, hoping they'd be passed along. I graduated with honors. I became a doctor.\n\nTwenty years later, I set up my own anonymous scholarship fund. Somewhere out there, students are receiving the same mysterious gift I did. The kindness keeps circling.\n\nTo my unknown benefactor: you changed my life. I'm paying it forward forever.",
                'excerpt' => 'An anonymous donor\'s generosity created a legacy of giving.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['education', 'scholarship', 'generosity', 'paying-it-forward'],
            ],
            [
                'title' => 'The Grocery Store Guardian',
                'content' => "I was in the grocery checkout with my three kids, exhausted and frazzled. My card was declined. I didn't have another one.\n\nI started putting items back, trying not to cry, trying to figure out which things we could live without. My kids were confused and upset.\n\nThe woman behind me stepped forward. \"I've got it,\" she said quietly. The whole bill—$150.\n\nI tried to get her information, to pay her back somehow. She refused. \"I've been where you are,\" she said. \"Just help someone else someday.\"\n\nI have. Many times. Her kindness taught me that we rise by lifting others.",
                'excerpt' => 'A stranger\'s generosity in a moment of embarrassment.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['strangers', 'motherhood', 'generosity', 'struggle'],
            ],
            [
                'title' => 'The Note in the Library Book',
                'content' => "I found a note tucked inside a library book: \"If you're reading this, I hope you know that you matter. You are worthy of love. Keep going.\"\n\nI don't know who wrote it. I don't know if they knew it would find someone who needed it. But that day, I was at my lowest point, questioning whether I should keep going at all.\n\nThat anonymous note stopped me. Someone out there—a stranger—believed in people they'd never meet. How could I give up when strangers were cheering me on?\n\nNow I leave similar notes in library books. You never know who needs to find one.",
                'excerpt' => 'An anonymous note in a library book arrived when it was needed most.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['books', 'notes', 'anonymous', 'hope'],
            ],
            [
                'title' => 'Teaching Kindness at Five',
                'content' => "My five-year-old daughter gave her lunch to a homeless man. Just walked up to him and handed over her sandwich. \"You look hungry,\" she said.\n\nI started to apologize—she was supposed to eat that. But the man's eyes filled with tears. \"No one has talked to me in three days,\" he said. \"Thank you for seeing me.\"\n\nI bought us all lunch that day. The three of us sat on a park bench together, eating sandwiches, talking about nothing and everything.\n\nMy daughter taught me something important: kindness doesn't need to be complicated. Sometimes it's just a sandwich and someone willing to see you.",
                'excerpt' => 'A five-year-old showed the adults what kindness really means.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['children', 'homelessness', 'compassion', 'simplicity'],
            ],
            [
                'title' => 'The Birthday Party Invite',
                'content' => "Every kid in my daughter's class was invited to Sarah's birthday party. Every kid except mine.\n\nI was heartbroken. My daughter was devastated. We spent that Saturday doing our own fun things, but the sting remained.\n\nMonday morning, the mom of another classmate called. She'd heard what happened. She organized a makeup party at her house—just for my daughter. Six kids came. There was cake and games and so much laughter.\n\nOne act of exclusion was answered by an act of radical inclusion. My daughter learned that for every unkindness, there are people ready to respond with love.",
                'excerpt' => 'When one party excluded, another mom created an answer of love.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['children', 'exclusion', 'friendship', 'parenting'],
            ],
            [
                'title' => 'The Coat in Winter',
                'content' => "I saw him shivering at the bus stop in December. Thin jacket, no gloves, clearly suffering. I had two coats—one on my body, one in my bag.\n\nI almost walked by. It felt awkward, intrusive. What if he was offended?\n\nThen I thought: what if no one else stops? What if I'm the only person today who can help?\n\nI gave him my spare coat. His hands shook as he put it on. \"God bless you,\" he whispered. \"God bless you.\"\n\nI still think about that moment. The seconds of awkwardness were nothing compared to knowing he was warm that night.",
                'excerpt' => 'Overcoming awkwardness to give someone warmth in the cold.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['winter', 'strangers', 'generosity', 'homelessness'],
            ],
            [
                'title' => 'The Dog Walker\'s Secret',
                'content' => "My elderly neighbor couldn't walk her dog anymore. Her arthritis had gotten too bad. She was devastated—her dog was her best friend, her reason to get up in the morning.\n\nI started walking her dog on my morning runs. It added maybe fifteen minutes to my routine. No big deal.\n\nBut to her, it was everything. \"You've given me back my joy,\" she told me, tears in her eyes. \"That dog is all I have.\"\n\nShe passed away last year. The dog lives with me now. And every morning when I walk him, I think of her and how tiny kindnesses can mean the world.",
                'excerpt' => 'Walking a neighbor\'s dog became an unexpected gift for everyone.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['neighbors', 'dogs', 'elderly', 'community'],
            ],
            [
                'title' => 'The Uber Driver\'s Detour',
                'content' => "My Uber driver noticed I was crying in the backseat. I was on my way to the hospital—my father was dying.\n\nWithout a word, he drove past a flower shop and pulled over. \"Wait here,\" he said. He came back with a small bouquet. \"For your father. And for you.\"\n\nI couldn't speak. I just held the flowers and cried harder.\n\nWhen we arrived at the hospital, he wouldn't accept payment for the ride or the flowers. \"We're all going through something,\" he said. \"Sometimes we just need someone to notice.\"\n\nI gave my father those flowers. They were the last thing he saw before he closed his eyes.",
                'excerpt' => 'An Uber driver\'s compassion created a final gift for a dying man.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['strangers', 'death', 'compassion', 'flowers'],
            ],
            [
                'title' => 'Paying the Toll',
                'content' => "I pay the toll for the car behind me every time I use the highway. It started as an accident—I had extra cash and was feeling generous. Now it's a habit.\n\nI'll never see those drivers' faces. I'll never know if they needed it or not. But I love imagining their moment of confusion turning into a smile.\n\nKindness doesn't have to be personal. Sometimes it's just a small, anonymous gift—a reminder that strangers can care about each other. That's the world I want to live in, and I'm creating it one toll at a time.",
                'excerpt' => 'A simple highway habit spreads anonymous joy.',
                'category' => 'kindness',
                'author_type' => AuthorType::Self,
                'tags' => ['anonymous', 'driving', 'generosity', 'habits'],
            ],

            // PERSEVERANCE (12 stories)
            [
                'title' => 'Nine Years to Overnight Success',
                'content' => "People call me an overnight success. It makes me laugh. They didn't see the nine years before \"overnight.\"\n\nNine years of working two jobs while building my business at 4 AM. Nine years of rejection emails. Nine years of everyone telling me to give up and get a \"real\" job.\n\nThen one article went viral. One investor said yes. Suddenly I was an \"overnight success.\"\n\nThere's no such thing. Every success is built on years of invisible work. Every peak is climbed step by invisible step. Don't let anyone make you feel like you're failing just because you're still climbing.",
                'excerpt' => 'The invisible work behind what others call overnight success.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['success', 'hard-work', 'entrepreneurship', 'patience'],
            ],
            [
                'title' => 'Learning to Walk Again (Again)',
                'content' => "I've had to learn to walk three times in my life. Once as a baby. Once after a car accident at nineteen. Once after a stroke at fifty-two.\n\nEach time, I thought I'd never do it. Each time, the work was grueling, humiliating, exhausting. Each time, I wanted to give up.\n\nBut there's something about watching your leg move an inch farther than yesterday. Something about standing unsupported for one more second. Progress in tiny increments is still progress.\n\nI'm walking again now. Slowly, with a cane, but walking. And I've learned: the human body wants to heal. You just have to keep showing up.",
                'excerpt' => 'Three times she lost the ability to walk. Three times she fought back.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['disability', 'recovery', 'determination', 'healing'],
            ],
            [
                'title' => 'The Dissertation That Took Ten Years',
                'content' => "I started my dissertation in my thirties. I finished it in my forties. In between: two children, a divorce, three job changes, my mother's death, and a global pandemic.\n\nEvery year I thought about quitting. Every year, something made me stay. Maybe stubbornness. Maybe the sunk cost. Maybe the small voice that said I could do this if I just kept going.\n\nI defended my dissertation the week of my forty-third birthday. My kids were in the audience. The committee said I'd earned every word.\n\nTen years. One page at a time. It's not about speed—it's about not stopping.",
                'excerpt' => 'A decade-long academic journey through life\'s chaos.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['education', 'determination', 'parenthood', 'goals'],
            ],
            [
                'title' => 'Auditioning One More Time',
                'content' => "I'd auditioned for the same theater company fourteen times. Fourteen rejections. Every actor I knew told me to move on—they obviously didn't want me.\n\nBut I loved their work. I believed I could contribute. So I auditioned a fifteenth time.\n\nI got the part. Not only that—the director told me my persistence was what finally convinced them. \"We needed to know you really wanted it,\" he said. \"Now we know.\"\n\nThat role launched my career. All because I showed up one more time when everyone said to stop.",
                'excerpt' => 'Fourteen rejections didn\'t stop her from auditioning again.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['acting', 'rejection', 'persistence', 'career'],
            ],
            [
                'title' => 'Sobriety Day One (Again)',
                'content' => "I've had a hundred Day Ones. Maybe more. Each time I fell off the wagon, the shame was crushing. Why couldn't I do this? Why was I so weak?\n\nThen a counselor reframed it for me. \"Every Day One means you haven't given up,\" she said. \"It means you're still fighting. That's not weakness—that's courage.\"\n\nI'm on Day 847 now. It might become Day One again someday. But even if it does, I'll start over. Because giving up isn't an option, and every new Day One is proof that I'm still in the fight.",
                'excerpt' => 'Reframing countless relapses as proof of ongoing courage.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['sobriety', 'addiction', 'recovery', 'determination'],
            ],
            [
                'title' => 'Building a House Brick by Brick',
                'content' => "I couldn't afford a contractor, so I built my own house. Me, YouTube tutorials, and seven years of weekends.\n\nPeople thought I was crazy. \"You don't know anything about construction,\" they said. They were right. I learned as I went. I made mistakes. I tore down walls and rebuilt them. I cried in frustration more times than I can count.\n\nBut last month, I moved in. Every brick, every nail, every paint stroke—mine. It's not perfect, but it's proof that you can build anything if you refuse to stop.",
                'excerpt' => 'Seven years of weekends built a house from nothing.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['construction', 'self-taught', 'determination', 'goals'],
            ],
            [
                'title' => 'The Book No One Wanted',
                'content' => "My book was rejected by over a hundred publishers. I papered my wall with rejection letters—a monument to failure.\n\nI self-published because I believed in the story. I sold copies out of my trunk. I spoke at libraries for audiences of three people.\n\nTen years later, a publisher called. They'd seen my grassroots following and wanted to republish the book. It became a bestseller.\n\nBut here's what matters: even if it hadn't, I'd have no regrets. I got my story into the world. The success is secondary to the persistence.",
                'excerpt' => 'A hundred rejections couldn\'t stop this story from being told.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['writing', 'rejection', 'self-publishing', 'determination'],
            ],
            [
                'title' => 'Training Through Injury',
                'content' => "The doctors said I'd never run competitively again. My knee injury was too severe. I should be grateful I could walk.\n\nI was grateful. But I wasn't done. I found doctors who specialized in athletes. I did physical therapy for two years. I retrained my body to move differently.\n\nLast year, I completed an ultramarathon. Not at my old speed—but I finished. My knee held. And I proved that \"never\" is often just a starting point for those who refuse to accept it.",
                'excerpt' => 'When doctors said never, she heard \"not yet.\"',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['running', 'injury', 'recovery', 'determination'],
            ],
            [
                'title' => 'Failing the Bar Five Times',
                'content' => "I failed the bar exam five times. Every time, I had to tell my family, my friends, my employers. Every time, I saw the doubt in their eyes.\n\nThe sixth time, I passed. I'm now a practicing attorney who specializes in helping underprivileged clients.\n\nSometimes people ask if I'm embarrassed about failing so many times. I'm not. Those failures taught me resilience, humility, and determination. They made me a better lawyer and a better person.\n\nSuccess isn't about never failing. It's about never stopping.",
                'excerpt' => 'Five failures became the foundation for a legal career.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['law', 'failure', 'exams', 'determination'],
            ],
            [
                'title' => 'Climbing Out of Debt',
                'content' => "I was $150,000 in debt. Medical bills, student loans, credit cards I'd used to survive when I couldn't work. The number felt insurmountable.\n\nI made a plan. I took extra jobs. I cut every expense I could. I celebrated paying off fifty dollars like it was fifty thousand.\n\nEight years later, I made my final payment. I sat in my car and screamed with joy. Eight years of sacrifice, discipline, and believing that tiny progress was still progress.\n\nIf you're drowning in debt, I want you to know: you can climb out. It takes time. But it's possible. Keep swimming.",
                'excerpt' => 'Eight years of discipline conquered $150,000 in debt.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['debt', 'finances', 'discipline', 'determination'],
            ],
            [
                'title' => 'The Language of Patience',
                'content' => "I decided to learn Mandarin at fifty. Everyone said I was too old, that language acquisition is a young person's game.\n\nThey weren't entirely wrong. It was hard. Harder than anything I'd done in decades. I butchered tones. I forgot characters. I felt like a slow student in a class of quick learners.\n\nBut five years later, I had a full conversation with a vendor in Beijing. She complimented my accent. I almost cried in the middle of the market.\n\nYou're never too old to learn. You're just old enough to know it takes time.",
                'excerpt' => 'Learning Mandarin at fifty proved age is just a starting point.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['language', 'learning', 'age', 'determination'],
            ],
            [
                'title' => 'Two Hundred Job Applications',
                'content' => "After my layoff, I applied to two hundred jobs. Two hundred. I kept a spreadsheet—company, date, response. Most boxes stayed empty.\n\nRejections came. Ghosting came. One interview ended when they realized I was \"overqualified.\" Another when they found someone cheaper.\n\nBut I kept applying. Every morning, five more applications. Every rejection, one more try.\n\nJob number two hundred and three said yes. It wasn't my dream job. But it paid the bills and led to better things. And I learned: you only need one yes. You just have to outlast the nos.",
                'excerpt' => 'Two hundred rejections before finding the one yes that mattered.',
                'category' => 'perseverance',
                'author_type' => AuthorType::Self,
                'tags' => ['career', 'job-hunting', 'rejection', 'determination'],
            ],

            // LOVE & FAMILY (13 stories)
            [
                'title' => 'My Father\'s Last Lesson',
                'content' => "My father spent his final weeks teaching me to make his spaghetti sauce. He was dying—we both knew it—but he didn't want to talk about death. He wanted to cook.\n\nEvery day, we'd stand in the kitchen together. Him weaker, me measuring. Him tasting, me adjusting. Him passing down generations of knowledge through tomatoes and garlic.\n\nNow, when I make that sauce, I feel him next to me. I hear his voice saying \"more basil\" and \"lower the heat.\" He's been gone five years, but in my kitchen, he's always here.",
                'excerpt' => 'A dying father\'s recipe became an eternal connection.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['father', 'cooking', 'grief', 'legacy'],
            ],
            [
                'title' => 'Choosing Each Other Again',
                'content' => "After twenty years of marriage, we almost got divorced. We'd grown apart, stopped seeing each other, become roommates instead of partners.\n\nBut in counseling, something shifted. We remembered why we'd fallen in love. We chose to fall again—deliberately, intentionally, with full knowledge of each other's flaws.\n\nOur marriage now is deeper than our first marriage ever was. We don't take each other for granted. We choose each other every morning, every argument, every ordinary day.\n\nLove isn't just a feeling. It's a choice. And sometimes choosing again is more powerful than choosing the first time.",
                'excerpt' => 'A marriage nearly lost was rebuilt through daily choosing.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['marriage', 'love', 'counseling', 'commitment'],
            ],
            [
                'title' => 'The Brother I Almost Lost',
                'content' => "We hadn't spoken in seven years. A stupid argument had spiraled into stubborn silence. I thought about calling a thousand times but never did.\n\nThen I heard he was in the hospital. I drove eight hours through the night, terrified I'd be too late.\n\nHe was awake when I got there. \"I'm sorry,\" I said immediately. \"I'm so sorry.\"\n\n\"Me too,\" he whispered.\n\nSeven years of silence ended in two words. He recovered. We talk every week now. And I'll never let pride steal time from us again.",
                'excerpt' => 'Seven years of silence ended at a hospital bedside.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['siblings', 'forgiveness', 'family', 'healing'],
            ],
            [
                'title' => 'Adopting at Fifty',
                'content' => "We were told we were too old to adopt. Multiple agencies turned us away. \"Kids need younger parents,\" they said. \"You won't have the energy.\"\n\nBut one agency took a chance on us. And two years ago, we brought home our daughter. She was eight, had been in foster care for years, and needed exactly what we had to offer: stability, patience, and so much love.\n\nShe's ten now. She calls us Mom and Dad. And our \"old\" energy? Turns out it's just right for reading bedtime stories, helping with homework, and being present.\n\nFamily doesn't have an age limit.",
                'excerpt' => 'Age couldn\'t stop them from becoming parents.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['adoption', 'parenthood', 'age', 'family'],
            ],
            [
                'title' => 'The Voicemail I Saved',
                'content' => "My mom left me a voicemail the day before she died unexpectedly. Just a normal message: \"Hi honey, just thinking of you. Call me back when you can. I love you.\"\n\nI've saved that voicemail for six years. Sometimes I listen to it when I miss her most. Her voice, her \"I love you,\" the way she said my name.\n\nI tell everyone now: save the voicemails. Record your parents' voices. Take videos of ordinary moments. You don't know which ones will become priceless.",
                'excerpt' => 'An ordinary voicemail became an irreplaceable treasure.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['mother', 'grief', 'memory', 'loss'],
            ],
            [
                'title' => 'A Letter Every Year',
                'content' => "Since my daughter was born, I've written her a letter every year on her birthday. I tell her what she's like that year, what makes her laugh, what she's struggling with, what I love about her.\n\nShe doesn't know about the letters yet. She's only twelve. I plan to give them to her when she turns eighteen—a box of seventeen letters, a record of her entire childhood through my eyes.\n\nSomeday she'll read about the toddler who loved butterflies, the seven-year-old who wrote poetry, the twelve-year-old who's just starting to find herself. And she'll know: she was loved, fully and completely, every single year.",
                'excerpt' => 'Birthday letters are building a treasure for her future self.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['parenting', 'letters', 'love', 'tradition'],
            ],
            [
                'title' => 'Finding My Birth Mother',
                'content' => "I was adopted as an infant. For forty years, I wondered about my birth mother. Who was she? Why did she give me up? Did she ever think about me?\n\nWhen DNA testing became available, I found her. We met in a coffee shop—two strangers who shared blood and nothing else.\n\nShe told me her story. Teenage pregnancy, no support, impossible choices. She'd thought about me every day of her life.\n\nWe're not mother and daughter in the traditional sense. But we're connected now. And we both have answers to questions we've carried for decades.",
                'excerpt' => 'DNA testing answered forty years of questions.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['adoption', 'identity', 'reunion', 'dna'],
            ],
            [
                'title' => 'Three Generations of Bread',
                'content' => "My grandmother taught my mother to make bread. My mother taught me. Now I'm teaching my daughter.\n\nIt's the same recipe, passed down through four generations. The same movements—kneading, folding, waiting. The same kitchen filled with flour dust and warmth.\n\nWhen we bake together, I feel my grandmother's hands guiding mine, though she's been gone for twenty years. I feel my mother beside me, though she lives three states away.\n\nFood is memory. Food is connection. Every loaf carries our whole history.",
                'excerpt' => 'A bread recipe carries four generations of love.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['traditions', 'baking', 'generations', 'family'],
            ],
            [
                'title' => 'When My Son Came Out',
                'content' => "My son was terrified to tell us he was gay. He'd seen the news, heard stories of parents who rejected their children. He'd prepared for the worst.\n\nWhen he finally told us, I hugged him. \"I know,\" I said. \"I've known for years. And I love you exactly as you are.\"\n\nHe cried for an hour. Years of fear, released in one moment. All that worry, all that hiding, for nothing.\n\nParents, please: make it safe for your children to tell you anything. Let them know your love isn't conditional. They need to hear it before they find the courage to speak.",
                'excerpt' => 'A son\'s greatest fear met with complete acceptance.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['lgbtq', 'parenting', 'acceptance', 'love'],
            ],
            [
                'title' => 'The Stepfather Who Showed Up',
                'content' => "My biological father left when I was three. For years, I felt the gap, the missing piece.\n\nThen my mom married Tom. He didn't try to replace my father. He just showed up, day after day. He taught me to ride a bike. He helped with homework. He sat in the audience at every school play.\n\nWhen I got married, I asked him to walk me down the aisle. He cried. So did I.\n\n\"You're not my stepfather,\" I told him. \"You're my dad. Because dad is a verb, and you've been doing it my whole life.\"",
                'excerpt' => 'A stepfather earned the title \"Dad\" through years of presence.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['stepfamily', 'father', 'love', 'presence'],
            ],
            [
                'title' => 'Love After Sixty',
                'content' => "I thought love was over for me. My husband of thirty-five years passed away, and I couldn't imagine my heart opening again.\n\nThen I met Robert at a grief support group. He understood loss. He wasn't trying to replace my husband. He was offering something different: companionship for this new chapter.\n\nWe got married at sixty-seven. My children stood beside me. We danced our first dance to a song we both loved.\n\nLove doesn't have an expiration date. And the heart's capacity for it never runs out.",
                'excerpt' => 'Finding new love after loss in the later chapters of life.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['love', 'grief', 'remarriage', 'aging'],
            ],
            [
                'title' => 'My Sister\'s Keeper',
                'content' => "When my sister got sick, I moved in to help. I thought it would be temporary—a few months at most.\n\nFour years later, I'm still here. I've become her caregiver, her advocate, her constant companion. I've put my own life on hold, and sometimes I resent it.\n\nBut then she laughs at an old joke only we understand, and I remember: this is my sister. The one who taught me to read. The one who defended me against bullies. The one who knows me better than anyone.\n\nTaking care of her isn't a sacrifice. It's love in action. And I'd do it all again.",
                'excerpt' => 'Caregiving became the deepest expression of sibling love.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['siblings', 'caregiving', 'illness', 'love'],
            ],
            [
                'title' => 'A Father at Last',
                'content' => "We tried for ten years to have a baby. Fertility treatments, failed adoptions, shattered hopes. Each disappointment felt like dying.\n\nLast year, we got the call: a birth mother had chosen us. Three weeks later, we brought our son home.\n\nHolding him for the first time, I understood: every heartbreak had led to this moment. Every \"no\" was directing us toward this specific \"yes.\" He was always meant to be ours.\n\nTo everyone still waiting for their miracle: hold on. Your child is finding their way to you.",
                'excerpt' => 'Ten years of heartbreak led to the perfect moment.',
                'category' => 'love-family',
                'author_type' => AuthorType::Self,
                'tags' => ['fertility', 'adoption', 'parenthood', 'hope'],
            ],

            // FAITH & HOPE (12 stories)
            [
                'title' => 'The Prayer I Almost Didn\'t Pray',
                'content' => "I'd stopped praying years ago. Religion felt hollow, faith felt foolish. But that night, desperate and alone, I found myself whispering into the darkness: \"If anyone's listening, I need help.\"\n\nNothing magical happened. No voice answered. But something shifted in me—a tiny crack where light could enter.\n\nThe next day, I made one small choice toward hope. Then another. Slowly, my life changed. I still don't know if anyone was listening. But I know that the act of asking for help opened me to receiving it.",
                'excerpt' => 'A desperate prayer became the beginning of healing.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['prayer', 'faith', 'hope', 'healing'],
            ],
            [
                'title' => 'Signs from Dad',
                'content' => "After my dad died, cardinals started appearing everywhere. One sat on my windowsill the morning of his funeral. One landed beside me at the cemetery. They kept coming, at impossible moments.\n\nI'm not sure I believe in signs. But I believe in comfort. And every time I see a cardinal, I feel my father near. I hear his voice saying, \"I'm still here. Keep going.\"\n\nMaybe it's coincidence. Maybe it's grief creating meaning. Maybe it's something more. All I know is: the cardinals bring me peace. And that's enough.",
                'excerpt' => 'Cardinals became messengers of comfort from a father gone.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['grief', 'signs', 'father', 'comfort'],
            ],
            [
                'title' => 'Faith Without Answers',
                'content' => "My child died. There's no theology that makes that okay. No explanation that brings comfort. No framework that helps me understand.\n\nBut somehow, I still believe. Not in a God who prevented this—clearly, that didn't happen. But in something larger than this moment of pain. In a love that death can't destroy. In a reunion I can't prove but can't stop hoping for.\n\nFaith isn't about having answers. It's about holding onto hope when everything says you shouldn't. It's choosing to believe that the story isn't over.",
                'excerpt' => 'Losing a child didn\'t end faith—it transformed it.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['grief', 'faith', 'loss', 'hope'],
            ],
            [
                'title' => 'The Church That Saved Me',
                'content' => "I walked into a church for the first time in twenty years, only because it was raining and I needed shelter. I planned to leave as soon as it stopped.\n\nAn older woman sat next to me. She didn't ask why I was there or try to convert me. She just said, \"You look like you could use a cup of coffee,\" and led me to the fellowship hall.\n\nThat coffee led to a conversation. That conversation led to a community. That community led to healing I didn't know I needed.\n\nSometimes grace shows up as a cup of coffee and a stranger's kindness.",
                'excerpt' => 'A rainstorm led to unexpected grace and community.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['church', 'community', 'grace', 'kindness'],
            ],
            [
                'title' => 'Hope in the Darkness',
                'content' => "My depression tells me there's no point. That nothing will get better. That the darkness is all there is.\n\nBut I've learned to hold onto hope even when I can't feel it. Hope as discipline, not emotion. Hope as showing up, taking medication, going to therapy, putting one foot in front of the other.\n\nI don't always believe things will improve. But I act as if they might. And sometimes, that's enough to get through. Sometimes, eventually, the darkness lifts. And I'm glad I stayed.",
                'excerpt' => 'When hope can\'t be felt, it can still be practiced.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['depression', 'hope', 'mental-health', 'survival'],
            ],
            [
                'title' => 'Finding God in Doubt',
                'content' => "I used to think doubt was the opposite of faith. That my questions meant I was failing somehow. That true believers never wondered.\n\nBut my doubts led me deeper. Questioning forced me to examine what I really believed, not just what I'd been told. Wrestling with hard truths made my faith stronger, not weaker.\n\nNow I see doubt as part of the journey. It's not a sign of weak faith—it's a sign of living faith. A faith that's never questioned is a faith that's never truly your own.",
                'excerpt' => 'Doubt became the path to a deeper, more authentic faith.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['faith', 'doubt', 'spirituality', 'growth'],
            ],
            [
                'title' => 'The Prayer Circle',
                'content' => "When I was diagnosed with cancer, my grandmother organized a prayer circle. Fourteen women from her church, meeting every Tuesday to pray for my healing.\n\nI'm not sure I believe in the power of prayer. But I know I felt loved. I knew that every Tuesday, fourteen women were thinking of me, holding space for my healing, sending their hopes into the universe on my behalf.\n\nI'm in remission now. Was it the chemotherapy? The prayers? Both? I don't know. But I know this: being held in love by others is its own kind of medicine.",
                'excerpt' => 'Whether or not prayers healed her body, they touched her heart.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['prayer', 'cancer', 'community', 'healing'],
            ],
            [
                'title' => 'Waiting for Spring',
                'content' => "In the darkest part of winter, it's hard to believe spring will come. The world is grey, the days are short, and warmth feels like a distant memory.\n\nBut spring always comes. Always. No matter how long winter lasts, the earth turns, the days lengthen, the flowers push through frozen ground.\n\nWhen life is winter—when grief or depression or fear has made everything cold—remember: spring always comes. You just have to survive until it does. Keep breathing. Keep waiting. The warmth will return.",
                'excerpt' => 'Nature\'s cycles offer a promise for life\'s winters.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['seasons', 'hope', 'nature', 'survival'],
            ],
            [
                'title' => 'The Miracle I Didn\'t Expect',
                'content' => "I prayed for a miracle: for my illness to be cured, for the test results to come back normal, for everything to be okay.\n\nThat's not the miracle I got. My illness remained. My results were bad. Everything was not okay.\n\nBut the miracle came anyway—in unexpected forms. Strangers who showed kindness. Strength I didn't know I had. Connection with others who understood. A depth of life I'd never experienced when everything was fine.\n\nMiracles don't always look like we expect. Sometimes they're hidden in the hard things.",
                'excerpt' => 'The miracle came, just not in the expected form.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['miracles', 'illness', 'hope', 'perspective'],
            ],
            [
                'title' => 'Losing and Finding Faith',
                'content' => "I lost my faith completely in my thirties. The beliefs I'd grown up with crumbled under scrutiny. I felt adrift, unmoored, spiritually homeless.\n\nFor years, I was an atheist. A content one. I found meaning in other ways.\n\nBut in my fifties, something called me back. Not to my childhood faith—that was gone forever. But to something new. A spirituality I'd built from scratch, examined, tested, chosen.\n\nLosing my faith was necessary. It let me find a faith that was actually mine.",
                'excerpt' => 'Sometimes you have to lose faith to find a truer version of it.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['faith', 'spirituality', 'journey', 'growth'],
            ],
            [
                'title' => 'The Reason to Stay',
                'content' => "I was planning to end my life. I'd chosen the day, the method, the note I'd leave behind. I was certain no one would miss me.\n\nThat morning, my neighbor knocked on my door. Her dog had puppies, and she wanted to show me. For twenty minutes, I held a tiny life in my hands. Something in me cracked open.\n\nI didn't go through with my plan. I called a helpline instead. That was three years ago.\n\nIf you're struggling, please hold on. You don't know what knock on the door tomorrow might bring. You don't know what reason to stay is waiting just around the corner.",
                'excerpt' => 'An unexpected knock became the reason to keep living.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Text,
                'author_text' => 'Anonymous',
                'tags' => ['suicide-prevention', 'hope', 'healing', 'intervention'],
            ],
            [
                'title' => 'Grace in the Grocery Store',
                'content' => "I was having a panic attack in the grocery store. I couldn't breathe, couldn't move, couldn't do anything but stand in the cereal aisle and shake.\n\nA woman approached me. Calmly, quietly, she said, \"I've been there. You're going to be okay. Just breathe with me.\" She breathed slowly, and I matched her. In and out. In and out.\n\nGradually, the panic released. When I could speak, I thanked her. \"That's what grace is,\" she said. \"Showing up for each other.\"\n\nI've never forgotten her. And I look for chances to show up for others the same way.",
                'excerpt' => 'A stranger\'s calm presence became unexpected grace.',
                'category' => 'faith-hope',
                'author_type' => AuthorType::Self,
                'tags' => ['anxiety', 'strangers', 'grace', 'healing'],
            ],

            // PERSONAL GROWTH (13 stories)
            [
                'title' => 'The Year I Said No',
                'content' => "For thirty years, I said yes to everything. Yes to extra work. Yes to toxic relationships. Yes to commitments I didn't want. I was exhausted, resentful, and depleted.\n\nThen I decided to spend one year saying no. No to anything that didn't align with my values. No to people who drained me. No to busyness for busyness's sake.\n\nThat year changed my life. I lost some relationships that needed losing. I gained time, energy, and clarity about what actually mattered.\n\nNo is a complete sentence. And sometimes it's the most important word you can say.",
                'excerpt' => 'Learning to say no reclaimed a life of purpose.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['boundaries', 'growth', 'self-care', 'priorities'],
            ],
            [
                'title' => 'Therapy Changed Everything',
                'content' => "I thought therapy was for \"crazy\" people. I thought I should be able to figure out my problems alone. I thought asking for help meant weakness.\n\nI was wrong about all of it.\n\nThree years of therapy helped me understand patterns I'd been repeating for decades. It showed me where my behaviors came from and how to change them. It gave me tools I use every single day.\n\nTherapy isn't weakness. It's one of the bravest things you can do. It means you're ready to look at yourself honestly—and that takes enormous courage.",
                'excerpt' => 'Overcoming stigma to find life-changing help.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['therapy', 'mental-health', 'growth', 'courage'],
            ],
            [
                'title' => 'Learning to Be Alone',
                'content' => "I'd never been alone. From my parents' house to college roommates to marriage, there was always someone there. When my divorce finalized, I was terrified.\n\nLiving alone for the first time at forty-five was uncomfortable, then lonely, then... peaceful. I learned who I was when no one was watching. I discovered what I liked, not what I should like. I became my own best company.\n\nI'm not alone anymore—I'm in a healthy relationship now. But I'll never regret that year of solitude. It introduced me to myself.",
                'excerpt' => 'Solitude after divorce became an introduction to herself.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['solitude', 'divorce', 'self-discovery', 'independence'],
            ],
            [
                'title' => 'The Apology I Owed',
                'content' => "Twenty years ago, I bullied a kid in high school. It haunted me—the memory of his face, the knowledge of what I'd done. But I never apologized. I told myself it was too late, that he'd probably forgotten, that reaching out would be weird.\n\nLast year, I found him on social media and sent a message. I apologized fully, without excuses or justification.\n\nHe wrote back. He said he'd carried that pain for decades. My apology, late as it was, gave him closure. It gave me closure too.\n\nIt's never too late to own your mistakes. Apologies can heal wounds decades old.",
                'excerpt' => 'An apology two decades late still brought healing.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['apology', 'bullying', 'growth', 'healing'],
            ],
            [
                'title' => 'Unlearning Perfection',
                'content' => "I was raised to be perfect. Perfect grades, perfect behavior, perfect appearance. Anything less was failure.\n\nIt took me forty years—and a breakdown—to realize: perfection is a prison. It keeps you small, afraid, and forever chasing an impossible standard.\n\nNow I deliberately do things imperfectly. I share work before it's polished. I let myself be messy, be wrong, be human. It feels terrifying and freeing all at once.\n\n\"Good enough\" isn't settling. It's permission to live fully instead of performing endlessly.",
                'excerpt' => 'Perfectionism was a prison; \"good enough\" became freedom.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['perfectionism', 'growth', 'self-acceptance', 'vulnerability'],
            ],
            [
                'title' => 'Facing the Fear',
                'content' => "I was terrified of public speaking. Heart-racing, voice-shaking, might-actually-vomit terrified. So I did the only logical thing: I signed up to give a TEDx talk.\n\nThe preparation was torture. The practice runs were humiliating. The night before, I almost canceled.\n\nBut I did it. My voice shook. My hands trembled. And when it was over, I cried in the bathroom.\n\nBut here's what changed: fear no longer runs my life. If I could do that—the scariest thing I could imagine—what else might be possible?",
                'excerpt' => 'Deliberately facing the worst fear changed everything.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['fear', 'public-speaking', 'courage', 'growth'],
            ],
            [
                'title' => 'The Morning Routine That Changed Me',
                'content' => "I used to start every day stressed—scrolling my phone, rushing through coffee, arriving everywhere already exhausted. Life felt like it was happening to me.\n\nOne experiment changed everything: waking up one hour earlier to do exactly what I wanted. Reading. Writing. Walking. Silence.\n\nThat stolen hour transformed the other twenty-three. I began days feeling centered instead of chaotic. I made better decisions. I had more patience. I actually enjoyed my life.\n\nHow you start your morning shapes your entire day. That hour was the best investment I ever made in myself.",
                'excerpt' => 'One hour stolen from sleep transformed every other hour.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['routine', 'morning', 'habits', 'wellness'],
            ],
            [
                'title' => 'Breaking the Family Cycle',
                'content' => "My father was angry. His father was angry. Generations of men in my family dealt with life through rage.\n\nWhen I caught myself screaming at my son—really screaming, veins popping, face red—I saw the cycle. I saw what I was passing down. I saw my father's face in the mirror.\n\nI started therapy the next week. I learned tools for anger. I apologized to my son and committed to change.\n\nBreaking a generational pattern is the hardest thing I've ever done. But my son will have a different story to tell. The cycle ends with me.",
                'excerpt' => 'A moment of rage sparked the decision to end a generational cycle.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['anger', 'parenting', 'generational-healing', 'therapy'],
            ],
            [
                'title' => 'The Comparison Trap',
                'content' => "I spent years measuring my success against others. Every friend's promotion, every colleague's achievement, every stranger's perfect Instagram life—I used them all as proof that I was falling behind.\n\nThe turning point came when I realized: comparison only steals joy. Someone else's success doesn't diminish mine. Life isn't a race, and even if it were, we're all running different courses.\n\nNow I celebrate others' wins genuinely. My only competition is yesterday's version of myself. And that's a much kinder race to run.",
                'excerpt' => 'Escaping the comparison trap brought genuine joy.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['comparison', 'social-media', 'self-acceptance', 'mindset'],
            ],
            [
                'title' => 'Learning to Rest',
                'content' => "I wore busyness like a badge of honor. Working through lunch, working late, working weekends. Rest felt lazy, indulgent, wrong.\n\nThen burnout caught up with me. My body simply stopped. Forced to rest, I discovered something shocking: I was more productive after rest. More creative. More present.\n\nRest isn't the opposite of productivity. It's the foundation of it. Now I guard my rest fiercely—not as a reward for work, but as a requirement for it.\n\nYou can't pour from an empty cup. Fill yours first.",
                'excerpt' => 'Burnout taught the counterintuitive value of rest.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['burnout', 'rest', 'productivity', 'self-care'],
            ],
            [
                'title' => 'Forgiving Myself',
                'content' => "I could forgive anyone except myself. Every mistake I'd ever made lived in my head, replaying endlessly. I was my own harshest critic, my own worst enemy.\n\nA friend asked me: \"Would you say those things to someone you love?\" The answer was obviously no. So why was I saying them to myself?\n\nLearning self-forgiveness was the hardest personal growth work I've done. But it was also the most necessary. You can't move forward while you're still punishing yourself for the past.",
                'excerpt' => 'Learning to treat herself with the grace she gave others.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['self-forgiveness', 'self-compassion', 'growth', 'healing'],
            ],
            [
                'title' => 'The Power of \"Yet\"',
                'content' => "My therapist taught me to add one word to my negative self-talk: yet.\n\nI can't do this... yet. I don't understand this... yet. I'm not good at this... yet.\n\nThat tiny word transforms failure into process. It turns fixed into growth. It reminds me that where I am now isn't where I have to stay.\n\nI use it constantly now. It's become a mental habit that's changed how I see challenges. Every \"I can't\" becomes an invitation to learn, not a life sentence.",
                'excerpt' => 'One word transformed failures into possibilities.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['mindset', 'growth', 'therapy', 'language'],
            ],
            [
                'title' => 'Finding My Voice at Last',
                'content' => "For decades, I spoke in hedges and qualifiers. \"I might be wrong, but...\" \"This is probably stupid...\" \"Sorry to interrupt...\" I made myself small before anyone else could.\n\nI started catching myself. Every time I apologized unnecessarily, I noticed. Every time I diminished my ideas, I caught it.\n\nSlowly, I learned to speak directly. To take up space. To share ideas without pre-emptively discounting them.\n\nMy thoughts aren't less valuable than anyone else's. It took forty years to learn that, but I finally believe it.",
                'excerpt' => 'Decades of self-diminishing gave way to confident presence.',
                'category' => 'personal-growth',
                'author_type' => AuthorType::Self,
                'tags' => ['confidence', 'communication', 'women', 'growth'],
            ],

            // RANDOM ACTS (12 stories)
            [
                'title' => 'The Flat Tire Angel',
                'content' => "My tire blew out on a deserted highway at midnight. I had no cell service and no idea how to change a tire. I was panicking.\n\nA car pulled over. A woman about my mother's age got out, asked if I was okay, and then proceeded to change my tire. She worked quickly, efficiently, like she'd done it a hundred times.\n\n\"My father taught me,\" she said when I thanked her. \"Now I teach everyone I can. You're next—learn to change a tire and help the next person.\"\n\nI learned that weekend. I've helped three stranded drivers since.",
                'excerpt' => 'A midnight rescue came with instructions to pay it forward.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['strangers', 'cars', 'help', 'pay-it-forward'],
            ],
            [
                'title' => 'The Restaurant Bill',
                'content' => "We were celebrating my parents' 50th wedding anniversary at a nice restaurant. Fifty years of marriage—we wanted to make it special.\n\nWhen we asked for the check, the waiter smiled. \"It's been taken care of.\" A couple at another table had paid our entire bill—five people, multiple courses, wine—and left without saying a word.\n\nWe never found out who they were. But that act of generosity became part of our family's anniversary story forever. Strangers made a special night magical.",
                'excerpt' => 'Anonymous strangers paid for a golden anniversary celebration.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['generosity', 'anniversary', 'strangers', 'celebration'],
            ],
            [
                'title' => 'Snow Shoveling Surprise',
                'content' => "After a major blizzard, I woke up dreading the hours of shoveling ahead. I'm sixty-three with a bad back—snow removal is my worst winter task.\n\nWhen I opened my door, my entire driveway was already cleared. So was my walkway. So were my steps.\n\nI asked my neighbors. None of them knew who'd done it. To this day, I have no idea who my secret snow shoveler was.\n\nBut every time it snows now, before I tackle my own driveway, I clear at least one neighbor's first. The mystery shoveler started something.",
                'excerpt' => 'A mysterious snow shoveler sparked a neighborhood tradition.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['neighbors', 'winter', 'anonymous', 'community'],
            ],
            [
                'title' => 'The Airport Upgrade',
                'content' => "I was flying home for my father's funeral, exhausted and grief-stricken. At the gate, a woman in a business suit approached me.\n\n\"I have a first-class upgrade I'm not going to use,\" she said. \"You look like you could use it more than me.\"\n\nI started to refuse—I couldn't accept such a gift from a stranger. She insisted. \"We all need help sometimes. Let me help you today.\"\n\nI cried in my first-class seat, but they were different tears. Grief mixed with gratitude. Sorrow mixed with the warmth of human kindness.",
                'excerpt' => 'A stranger\'s gift of comfort during unbearable grief.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['travel', 'grief', 'strangers', 'kindness'],
            ],
            [
                'title' => 'Quarters for Laundry',
                'content' => "In college, I was broke. Really broke. Couldn't-afford-laundry broke. I was in the laundromat counting my last quarters, realizing I didn't have enough.\n\nAn older woman at the next machine watched me counting and recounting. Without a word, she handed me a roll of quarters.\n\n\"I remember those days,\" she said. \"You'll get through them. And someday you'll hand quarters to someone else.\"\n\nI've handed out probably fifty rolls of quarters since then. Every time, I tell them the same thing.",
                'excerpt' => 'A roll of quarters started a decades-long chain of kindness.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['college', 'money', 'strangers', 'pay-it-forward'],
            ],
            [
                'title' => 'The Lost Wallet Return',
                'content' => "I lost my wallet containing $400 cash—my entire rent money. I tore apart my apartment, retraced my steps, resigned myself to catastrophe.\n\nTwo days later, it appeared in my mailbox. All cash intact, with a note: \"Found this in the parking lot. Hope it finds you well. —A neighbor.\"\n\nNo name. No request for a reward. Just a stranger doing the right thing when no one was watching.\n\nI've returned two lost wallets since then. Both times, the owners cried. Both times, I understood why.",
                'excerpt' => 'A returned wallet with $400 taught lessons about integrity.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['honesty', 'money', 'strangers', 'integrity'],
            ],
            [
                'title' => 'The Parking Meter Fairy',
                'content' => "I was rushing to a job interview when I realized my parking meter was about to expire. I was going to get a ticket, be late, and probably blow the interview.\n\nWhen I sprinted out after, the meter showed time remaining. A note was tucked under my wiper: \"Looked like you were in a hurry. Good luck with whatever you're doing! :)\"\n\nI got the job. I've always wondered if I should thank the parking meter fairy somehow.\n\nNow I carry extra quarters and add time to expired meters whenever I can. Somewhere, there's another person sprinting to something important.",
                'excerpt' => 'A quarter in a meter might have changed a career trajectory.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['parking', 'interview', 'strangers', 'timing'],
            ],
            [
                'title' => 'Flowers for the Nurse',
                'content' => "During my hospital stay, one nurse went above and beyond. She remembered my name, held my hand during scary procedures, and treated me like a person, not just a patient.\n\nOn my discharge day, I sent flowers to the nurses' station with her name on them. A small gesture for everything she'd done.\n\nMonths later, I got a letter. She said those flowers came on her hardest day—she'd been considering quitting nursing entirely. The flowers reminded her why she started.\n\nYou never know when a small kindness might save someone.",
                'excerpt' => 'Flowers for a nurse arrived on the day she needed them most.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['nurses', 'hospital', 'appreciation', 'timing'],
            ],
            [
                'title' => 'The Book Left Behind',
                'content' => "Someone left a book on a park bench with a note: \"This book changed my life. I hope it changes yours too. Please pass it on when you're done.\"\n\nI read it. It did change something in me. When I finished, I left it on a coffee shop table with the same note.\n\nI wonder sometimes how many people have read that copy. How many lives it's touched. How far it's traveled from that park bench.\n\nKindness is like that book—it doesn't stop with you. Pass it on.",
                'excerpt' => 'A traveling book carries its message from reader to reader.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['books', 'sharing', 'community', 'chain'],
            ],
            [
                'title' => 'Pizza for the Fire Department',
                'content' => "I drove past my local fire station every day. One day, on impulse, I stopped and ordered pizzas for the crew. No special occasion. Just because.\n\nThe firefighters were confused at first—\"Is there a reason for this?\"—then genuinely touched. \"People usually only thank us after we save something,\" one said. \"This is just... nice.\"\n\nNow I do it randomly, maybe once a month. Different firehouses, police stations, hospitals. The look of surprise and gratitude never gets old.",
                'excerpt' => 'Random pizza deliveries became a way to honor everyday heroes.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['firefighters', 'pizza', 'appreciation', 'heroes'],
            ],
            [
                'title' => 'The Concert Ticket',
                'content' => "I had an extra ticket to my favorite band. My friend canceled last minute, and I couldn't find anyone to take it.\n\nOutside the venue, I found a teenager looking longingly at the marquee. \"Do you want to go?\" I asked, offering the ticket.\n\nHer face lit up like sunrise. She was a huge fan but couldn't afford tickets. She cried. I almost cried.\n\nI'll never forget her face when the band played her favorite song. Sometimes the best use of something isn't keeping it—it's giving it away.",
                'excerpt' => 'An extra ticket became a dream come true for a stranger.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['concert', 'generosity', 'strangers', 'music'],
            ],
            [
                'title' => 'The Compliment Collection',
                'content' => "I started a strange habit: giving genuine compliments to strangers. Your earrings are beautiful. That color looks amazing on you. Your laugh is infectious.\n\nAt first it felt awkward. Some people were suspicious. But most smiled, surprised and pleased.\n\nOne woman stopped me. \"You don't know how much I needed that today,\" she said, eyes filling. \"I was feeling invisible.\"\n\nThat's when I understood: we're all walking around starving for acknowledgment. A genuine compliment costs nothing and can change someone's entire day.",
                'excerpt' => 'A habit of complimenting strangers revealed a universal hunger.',
                'category' => 'random-acts',
                'author_type' => AuthorType::Self,
                'tags' => ['compliments', 'strangers', 'connection', 'kindness'],
            ],
        ];
    }
}
