<?php

namespace Database\Seeders;

use Database\Seeders\Concerns\SeedsFromJson;
use Illuminate\Database\Seeder;

/**
 * Dedicated LDS temples from the database/data/seed/temples.json snapshot —
 * name, address, coordinates, photo URL, and first dedication day.
 *
 * The snapshot is regenerated by `php artisan temples:import` (scrapes
 * churchofjesuschristtemples.org) followed by `php artisan
 * db:snapshot-seed-data`; normal seeding never touches the network.
 */
class TempleSeeder extends Seeder
{
    use SeedsFromJson;

    public function run(): void
    {
        $n = $this->seedFromJson('temples.json', 'temples');
        $this->command?->info("  Seeded {$n} temples.");
    }
}
